### PR TITLE
Latest apache http client version

### PR DESCRIPTION
**Pull request by fhoeben**
- Use latest apache http client
- By default use 'standard' cookie handling
- No longer allow cookie 'version' to be set when copying browser cookies (it shouldn't be needed)
- Make http client configuration easier to change from Java code
- Allow http client usage to be modified more easily by creating subclass

### CODE REVIEW

**Comment by fhoeben** [comment]
@ilseh does this change impact your testset (using the Fit based fixtures)? Can you test to see whether you experience any problems using the project from this branch? Thanks.

**Comment by ilseh** [comment]
@fhoeben i'm not sure when we have the opportunity to check this. Aiming at this friday for now.

**Comment by fhoeben** [comment]
@ilseh Did you have a chance to look at it?

**Comment by ilseh** [comment]
Unfortunately not. I don't know when we'll have the time.

**Pull request merged**
