### PR TITLE
Fix bug for FileFixture.setDirectory("http://files/test")

### PR DESCRIPTION
**Pull request by pvbemmelen62**
Fix bug in FileFixture.setDirectory(String)  for argument "http://files/test" .

Bug can be observed throught script:
<pre>
|Import                       |
|nl.hsac.fitnesse.fixture.slim|

|script       |file fixture     |
|set directory|http://files/test|
|show         |get directory    |

^|script|
|set  directory|http://files/test|
|show          |get directory    |
</pre>

For my project, the first set directory/get directory will show
`     C:\git\toolchain\wiki\FitNesseRoot\files\test\`
and the second one shows
`     C:\git\toolchain\wiki\FitNesseRoot\files\\files\test\`

The first one is right.
The difference comes from the fact that the first call to setDirectory() gets argument `<a href="files/test">http://files/test</a>` .

In the code, for the second call to setDirectory() :
<pre>
    public void setDirectory(String aDirectory) {
        if (this.isFilesUrl(aDirectory)) {
            String url = this.getUrl(aDirectory);
            String relativeDir = url.substring("files".length());             <<<<< goes wrong for url: http://files/test
            relativeDir = relativeDir.replace('/', File.separatorChar);
            this.directory = this.filesDir + relativeDir;
        } else if ((new File(aDirectory)).isAbsolute()) {
            this.directory = aDirectory;
        } else {
            this.directory = (new File(this.getEnvironment().getFitNesseDir(), aDirectory)).getAbsolutePath();
        }

        if (!this.directory.endsWith(File.separator)) {
            this.directory = this.directory + File.separator;
        }

    }
</pre>
Line
<pre>            String relativeDir = url.substring("files".length());</pre>
for url `http://files/test`  should produce `/test` but it doesn't.

Replace
<pre>            String relativeDir = url.substring("files".length());</pre>
by
<pre>            String relativeDir = url.substring(url.indexOf("files") + "files".length());</pre>

### CODE REVIEW

**Comment by fhoeben** [comment]
@pvbemmelen62 sorry it took me so long to respond. Seems like a good fix, can you maybe add unit tests to ensure both code paths (the normal and the escaped table) work?

**Comment by pvbemmelen62** [comment]
I've added two tests in src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java .
Are they what you asked for ?
And do I have to create a new pull request now that I added these tests, or can you get them from the current/open pull request ?
And ... oh yes... I haven't tested these two tests; I don't know how to run FileFixtureTest ; I've tried "mvn test" but I get
Failed to execute goal com.github.webdriverextensions:webdriverextensions-maven-plugin:3.4.0:install-driver
because of some connection failure.

**Comment by fhoeben** [comment]
@pvbemmelen62 I don't know what connection error you get, but according to my GitHub build the code doesn't compile...


```
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/hsac-fitnesse-fixtures/hsac-fitnesse-fixtures/src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java:[53,40] ')' expected
Error:  /home/runner/work/hsac-fitnesse-fixtures/hsac-fitnesse-fixtures/src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java:[53,45] illegal start of expression
Error:  /home/runner/work/hsac-fitnesse-fixtures/hsac-fitnesse-fixtures/src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java:[53,50] ';' expected
```

**Comment by fhoeben** [comment]
```
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/hsac-fitnesse-fixtures/hsac-fitnesse-fixtures/src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java:[46,36] cannot find symbol
  symbol:   variable defaultsFilesDir
  location: class nl.hsac.fitnesse.fixture.slim.FileFixtureTest
Error:  /home/runner/work/hsac-fitnesse-fixtures/hsac-fitnesse-fixtures/src/test/java/nl/hsac/fitnesse/fixture/slim/FileFixtureTest.java:[54,36] cannot find symbol
  symbol:   variable defaultsFilesDir
  location: class nl.hsac.fitnesse.fixture.slim.FileFixtureTest
```

**Pull request merged**
