### PR TITLE
Update chromium based webdrivers to 111

### PR DESCRIPTION
**Pull request by timovd**
See https://stackoverflow.com/questions/75680149/unable-to-establish-websocket-connection for changes in starting browser (with UI) in SuiteSetUp

### CODE REVIEW

**Comment by timovd** [comment]
Same issue as last time: This version of ChromeDriver only supports Chrome version 111
Will probably take a few days to be fixed/updated on GitHub.

**Comment by timovd** [comment]
@fhoeben could you please run the test again?

**Comment by fhoeben** [comment]
@timovd I believe the new argument should probably also be added to:

-  https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/641dd5fb6f965352e2d85a152d3463298eddfd20/.github/workflows/other.yml#L33
- https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/641dd5fb6f965352e2d85a152d3463298eddfd20/.gitlab-ci.yml#L168
- https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/641dd5fb6f965352e2d85a152d3463298eddfd20/docker/chrome/Dockerfile#L21

**Comment by timovd** [comment]
@fhoeben https://stackoverflow.com/questions/75718422/org-openqa-selenium-remote-http-connectionfailedexception-unable-to-establish-w
If this is a bug in Selenium and assuming this will be fixed. These changes needs to be undone later.

**Pull request merged**
